## cross_validation

In [251]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [252]:
digits = load_digits()

In [253]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [254]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [271]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.33)

In [272]:
X_train

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  4., 13., ...,  7.,  0.,  0.],
       [ 0.,  0.,  7., ...,  9.,  1.,  0.],
       ...,
       [ 0.,  0.,  5., ..., 16.,  6.,  0.],
       [ 0.,  0.,  0., ..., 14.,  4.,  0.],
       [ 0.,  0.,  8., ...,  5.,  0.,  0.]])

In [273]:
y_train

array([4, 3, 8, ..., 9, 2, 3])

In [274]:
X_test

array([[ 0.,  0.,  6., ...,  1.,  0.,  0.],
       [ 0.,  0.,  3., ..., 14.,  3.,  0.],
       [ 0.,  0.,  6., ..., 12.,  1.,  0.],
       ...,
       [ 0.,  0., 15., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  3., ...,  8.,  0.,  0.]])

In [275]:
y_test

array([5, 0, 3, 4, 3, 2, 4, 3, 4, 0, 5, 5, 9, 8, 5, 2, 0, 3, 9, 8, 1, 5,
       4, 4, 8, 3, 8, 6, 9, 8, 5, 9, 6, 1, 1, 6, 4, 7, 1, 2, 5, 7, 1, 6,
       3, 6, 7, 8, 0, 5, 1, 8, 5, 2, 5, 5, 3, 9, 2, 4, 2, 9, 9, 5, 0, 4,
       6, 5, 0, 3, 1, 3, 5, 3, 3, 7, 3, 7, 2, 6, 3, 3, 4, 2, 3, 8, 9, 6,
       9, 5, 5, 5, 5, 4, 0, 1, 5, 8, 3, 9, 7, 3, 0, 2, 2, 1, 8, 7, 4, 1,
       7, 0, 5, 3, 4, 2, 4, 8, 9, 4, 5, 7, 0, 7, 9, 9, 7, 0, 0, 5, 2, 0,
       2, 9, 2, 7, 2, 4, 9, 0, 7, 1, 0, 4, 0, 2, 8, 0, 2, 6, 9, 9, 8, 1,
       7, 2, 4, 7, 8, 4, 2, 7, 6, 8, 1, 9, 7, 5, 3, 4, 3, 3, 8, 4, 0, 8,
       7, 3, 3, 2, 2, 3, 8, 4, 6, 0, 1, 1, 7, 1, 5, 6, 0, 6, 0, 4, 0, 3,
       7, 3, 9, 5, 8, 6, 1, 0, 5, 4, 6, 6, 9, 9, 6, 0, 8, 2, 3, 5, 9, 0,
       5, 5, 6, 9, 3, 9, 3, 2, 5, 8, 5, 8, 0, 4, 8, 7, 0, 9, 8, 2, 4, 2,
       9, 4, 7, 2, 0, 1, 5, 1, 6, 1, 0, 6, 3, 9, 7, 6, 6, 0, 3, 0, 1, 3,
       6, 1, 0, 0, 6, 8, 5, 7, 9, 4, 2, 5, 9, 5, 8, 2, 7, 0, 1, 1, 9, 8,
       8, 3, 8, 6, 6, 7, 3, 5, 7, 7, 9, 8, 8, 6, 7,

In [276]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [277]:
reg = LogisticRegression(solver='liblinear',warm_start='False',multi_class='ovr')
reg.fit(X_train,y_train)
reg.score(X_test,y_test)

0.9595959595959596

In [278]:
reg1 =SVC(gamma='auto')
reg1.fit(X_train,y_train)
reg1.score(X_test,y_test)

0.5151515151515151

In [279]:
reg2 = RandomForestClassifier(n_estimators=30)
reg2.fit(X_train,y_train)
reg2.score(X_test,y_test)

0.9764309764309764

## k_fold

In [280]:
from sklearn.model_selection import KFold
a = KFold(n_splits=3)


In [281]:
for train_data,test_data in a.split([1,2,3,4,5,6,7,8,9]):
    print(train_data,test_data)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


###  StratifiedKFold

In [290]:
from sklearn.model_selection import StratifiedKFold

In [291]:
b = StratifiedKFold(n_splits=3)

In [300]:
scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in b.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))
    

In [301]:

scores_logistic

[0.8953488372093024, 0.9499165275459098, 0.9093959731543624]

In [302]:
scores_svm

[0.39368770764119604, 0.41068447412353926, 0.4597315436241611]

In [303]:
scores_rf

[0.925249169435216, 0.9482470784641068, 0.9345637583892618]

## cross_val_score

In [304]:
from sklearn.model_selection import cross_val_score

In [305]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3)

array([0.89534884, 0.94991653, 0.90939597])

In [307]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)

array([0.39368771, 0.41068447, 0.45973154])

In [308]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target,cv=3)

array([0.91694352, 0.95492487, 0.91610738])