In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [58]:
df = pd.read_csv("spam.csv")
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [59]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [60]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [61]:
df.Message.value_counts()

Sorry, I'll call later                                                                                                                                                 30
I cant pick the phone right now. Pls send a message                                                                                                                    12
Ok...                                                                                                                                                                  10
Please call our customer service representative on FREEPHONE 0808 145 4742 between 9am-11pm as you have WON a guaranteed £1000 cash or £5000 prize!                     4
Say this slowly.? GOD,I LOVE YOU &amp; I NEED YOU,CLEAN MY HEART WITH YOUR BLOOD.Send this to Ten special people &amp; u c miracle tomorrow, do it,pls,pls do it...     4
                                                                                                                                                      

In [62]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [63]:
df['category_replcaed'] = df.Category.apply(lambda x: 1 if x=='spam' else 0)

In [64]:
df.head()

Category                                            Message  \
0      ham  Go until jurong point, crazy.. Available only ...   
1      ham                      Ok lar... Joking wif u oni...   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...   
3      ham  U dun say so early hor... U c already then say...   
4      ham  Nah I don't think he goes to usf, he lives aro...   

   category_replcaed  
0                  0  
1                  0  
2                  1  
3                  0  
4                  0

In [65]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message,df.category_replcaed, test_size=0.33, random_state=42)

In [66]:
from sklearn.feature_extraction.text import CountVectorizer

In [67]:
k = CountVectorizer()

In [68]:
X_train_replaced = k.fit_transform(X_train.values)

In [69]:
X_train_replaced.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [70]:
from sklearn.naive_bayes import MultinomialNB

In [71]:
reg = MultinomialNB()

In [72]:
reg.fit(X_train_replaced,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [75]:
j = [
    
    'i am kumar solutions and i called as a professor',
    'amazon got 20% discount in sales'
    
]
emails_count = k.transform(j)
reg.predict(emails_count)

array([0, 0], dtype=int64)

In [76]:
y_test_pred = reg.predict(k.transform(X_test))

In [77]:
from sklearn.metrics import accuracy_score


In [78]:
accuracy_score(y_test,y_test_pred)

0.9902120717781403

In [79]:
emails = [
    
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = k.transform(emails)
reg.predict(emails_count)

array([0, 1], dtype=int64)