In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
from datetime import datetime,date,time
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor


In [2]:
data=pd.read_csv("kc_house_data.csv")
data.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view     ...      grade  sqft_above  \
0      5650     1.0           0     0     ...          7        1180   
1      7242     2.0           0     0     ...          7        2170   
2     10000     1.0           0     0     ...          6         770   
3      5000     1.0           0     0     ...          7        1050   
4      8080     1.0           0     0     ...          8        1680   

   sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0              0      1955             0    98178  47.5112 -122.257   
1            400      1951          1991    98125  47.7210 -122.319   
2              0      1933             0    98028  47.7379 -122.233   
3            910      1965             0    98136  47.5208 -122.393   
4              0      1987             0    98074  47.6168 -122.045   

   sqft_living15  sqft_lot15  
0           1340        5650  
1           1690        7639  
2           2720        8062  
3           1360        5000  
4           1800        7503  

[5 rows x 21 columns]

In [3]:
data.columns

Index([u'id', u'date', u'price', u'bedrooms', u'bathrooms', u'sqft_living',
       u'sqft_lot', u'floors', u'waterfront', u'view', u'condition', u'grade',
       u'sqft_above', u'sqft_basement', u'yr_built', u'yr_renovated',
       u'zipcode', u'lat', u'long', u'sqft_living15', u'sqft_lot15'],
      dtype='object')

head() is use for Returns the first five rows of the data set

In [4]:
data['date']=pd.to_datetime(data['date'])
data['month']=data['date'].dt.month
data['year']=data['date'].dt.year
data.head()


id       date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520 2014-10-13  221900.0         3       1.00         1180   
1  6414100192 2014-12-09  538000.0         3       2.25         2570   
2  5631500400 2015-02-25  180000.0         2       1.00          770   
3  2487200875 2014-12-09  604000.0         4       3.00         1960   
4  1954400510 2015-02-18  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...   sqft_basement  yr_built  \
0      5650     1.0           0     0  ...               0      1955   
1      7242     2.0           0     0  ...             400      1951   
2     10000     1.0           0     0  ...               0      1933   
3      5000     1.0           0     0  ...             910      1965   
4      8080     1.0           0     0  ...               0      1987   

   yr_renovated  zipcode      lat     long  sqft_living15  sqft_lot15  month  \
0             0    98178  47.5112 -122.257           1340        5650     10   
1          1991    98125  47.7210 -122.319           1690        7639     12   
2             0    98028  47.7379 -122.233           2720        8062      2   
3             0    98136  47.5208 -122.393           1360        5000     12   
4             0    98074  47.6168 -122.045           1800        7503      2   

   year  
0  2014  
1  2014  
2  2015  
3  2014  
4  2015  

[5 rows x 23 columns]

Using datetime extract the month and year

In [5]:
corr=data.corr()
corr.nlargest(24,'price')['price']

price            1.000000
sqft_living      0.702035
grade            0.667434
sqft_above       0.605567
sqft_living15    0.585379
bathrooms        0.525138
view             0.397293
sqft_basement    0.323816
bedrooms         0.308350
lat              0.307003
waterfront       0.266369
floors           0.256794
yr_renovated     0.126434
sqft_lot         0.089661
sqft_lot15       0.082447
yr_built         0.054012
condition        0.036362
long             0.021626
year             0.003576
month           -0.010081
id              -0.016762
zipcode         -0.053203
Name: price, dtype: float64

Using heatmap to obsearve the correlation between the features 

In [6]:
X=data[[u'sqft_living',u'waterfront', u'condition', u'grade',
       u'sqft_above',u'yr_renovated',u'lat', u'long', u'sqft_living15',u'year',u'zipcode',u'sqft_lot15']]
Y=data[['price']]

In [8]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=10)

House_Data can be split into training_data 80% and test_data 20%

In [9]:
#Decisiontree Regressor,BaggingRegressor
model = BaggingRegressor(base_estimator=DecisionTreeRegressor(max_depth=10), n_estimators=5,bootstrap=True, bootstrap_features=False, oob_score=True, n_jobs=3, random_state=2, verbose=1)
model.fit(X_train, Y_train)
model.predict(X_test)

C:\Users\RTS\Anaconda2\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
[Parallel(n_jobs=3)]: Done   3 out of   3 | elapsed:    2.8s finished
C:\Users\RTS\Anaconda2\lib\site-packages\sklearn\ensemble\bagging.py:987: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
[Parallel(n_jobs=3)]: Done   3 out of   3 | elapsed:    1.6s finished


array([ 394999.79930827,  643417.63316222,  335992.85949821, ...,
        833723.05459578,  426361.73150355,  480028.3169732 ])

   BaggingRegressor is used for the original dataset can be randomely predicted than (average/vote) the final prediction data

In [10]:
acc=model.score(X_train,Y_train) 
acc

[Parallel(n_jobs=3)]: Done   3 out of   3 | elapsed:    1.0s finished


0.91556370048030955

In [11]:
acc=model.score(X_test,Y_test) 
acc

[Parallel(n_jobs=3)]: Done   3 out of   3 | elapsed:    0.8s finished


0.86914522925926752

In [12]:
from sklearn.model_selection import cross_val_score
score=cross_val_score(model,X,Y,cv=2)
score

[Parallel(n_jobs=3)]: Done   3 out of   3 | elapsed:    1.5s finished
[Parallel(n_jobs=3)]: Done   3 out of   3 | elapsed:    0.9s finished
[Parallel(n_jobs=3)]: Done   3 out of   3 | elapsed:    1.5s finished
[Parallel(n_jobs=3)]: Done   3 out of   3 | elapsed:    0.7s finished


array([ 0.82453392,  0.79106396])

Cross validation is use for model performence on unseen data 

In [13]:
from sklearn.ensemble import RandomForestRegressor

In [14]:
model=RandomForestRegressor()
model.fit(X_train,Y_train)

C:\Users\RTS\Anaconda2\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [15]:
pred=model.predict(X_test)
pred

array([  445795. ,   620729.4,   278827.5, ...,  1006600. ,   476850. ,
         445650. ])

In [16]:
acc=model.score(X_test,Y_test)
acc

0.86169355787848667