In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("banking.csv")
data.head()

age          job  marital          education  default housing loan  \
0   44  blue-collar  married           basic.4y  unknown     yes   no   
1   53   technician  married            unknown       no      no   no   
2   28   management   single  university.degree       no     yes   no   
3   39     services  married        high.school       no      no   no   
4   55      retired  married           basic.4y       no     yes   no   

    contact month day_of_week  ...  campaign  pdays  previous     poutcome  \
0  cellular   aug         thu  ...         1    999         0  nonexistent   
1  cellular   nov         fri  ...         1    999         0  nonexistent   
2  cellular   jun         thu  ...         3      6         2      success   
3  cellular   apr         fri  ...         2    999         0  nonexistent   
4  cellular   aug         fri  ...         1      3         1      success   

  emp_var_rate  cons_price_idx  cons_conf_idx  euribor3m  nr_employed  y  
0          1.4          93.444          -36.1      4.963       5228.1  0  
1         -0.1          93.200          -42.0      4.021       5195.8  0  
2         -1.7          94.055          -39.8      0.729       4991.6  1  
3         -1.8          93.075          -47.1      1.405       5099.1  0  
4         -2.9          92.201          -31.4      0.869       5076.2  1  

[5 rows x 21 columns]

In [3]:
data.shape

(41188, 21)

In [4]:
data.isnull().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp_var_rate      0
cons_price_idx    0
cons_conf_idx     0
euribor3m         0
nr_employed       0
y                 0
dtype: int64

In [5]:
data.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp_var_rate', 'cons_price_idx',
       'cons_conf_idx', 'euribor3m', 'nr_employed', 'y'],
      dtype='object')

In [6]:
data["y"].unique()

array([0, 1], dtype=int64)

In [7]:
data["y"].value_counts()

0    36548
1     4640
Name: y, dtype: int64

In [8]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
feature=data.apply(label.fit_transform)
feature.head()

age  job  marital  education  default  housing  loan  contact  month  \
0   27    1        1          0        1        2     0        0      1   
1   36    9        1          7        0        0     0        0      7   
2   11    4        2          6        0        2     0        0      4   
3   22    7        1          3        0        0     0        0      0   
4   38    5        1          0        0        2     0        0      1   

   day_of_week  ...  campaign  pdays  previous  poutcome  emp_var_rate  \
0            2  ...         0     26         0         1             9   
1            0  ...         0     26         0         1             7   
2            2  ...         2      6         2         2             4   
3            0  ...         1     26         0         1             3   
4            0  ...         0      3         1         2             2   

   cons_price_idx  cons_conf_idx  euribor3m  nr_employed  y  
0              13             17        307           10  0  
1              11              7        267            9  0  
2              20             13         59            1  1  
3              10              3        221            6  0  
4               0             22        116            5  1  

[5 rows x 21 columns]

In [9]:
X=feature.drop(['y'],axis=1)
X.head()

age  job  marital  education  default  housing  loan  contact  month  \
0   27    1        1          0        1        2     0        0      1   
1   36    9        1          7        0        0     0        0      7   
2   11    4        2          6        0        2     0        0      4   
3   22    7        1          3        0        0     0        0      0   
4   38    5        1          0        0        2     0        0      1   

   day_of_week  duration  campaign  pdays  previous  poutcome  emp_var_rate  \
0            2       210         0     26         0         1             9   
1            0       138         0     26         0         1             7   
2            2       339         2      6         2         2             4   
3            0       185         1     26         0         1             3   
4            0       137         0      3         1         2             2   

   cons_price_idx  cons_conf_idx  euribor3m  nr_employed  
0              13             17        307           10  
1              11              7        267            9  
2              20             13         59            1  
3              10              3        221            6  
4               0             22        116            5

In [10]:
y=feature['y']
y.head()

0    0
1    0
2    1
3    0
4    1
Name: y, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,y,test_size=0.4,random_state=1)

In [12]:
from sklearn.tree import DecisionTreeClassifier

In [13]:
model=DecisionTreeClassifier()
model.fit(X_train,Y_train)

DecisionTreeClassifier()

In [14]:
y_pred=model.predict(X_test)
y_pred

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [19]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
accuracy_score(Y_test,y_pred)

0.8893542121874242

In [16]:
model.score(X_train,Y_train)

1.0

In [18]:
confusion_matrix(Y_test,y_pred)

array([[13681,   925],
       [  898,   972]], dtype=int64)

In [21]:
print(classification_report(Y_test,y_pred))

              precision    recall  f1-score   support

           0       0.94      0.94      0.94     14606
           1       0.51      0.52      0.52      1870

    accuracy                           0.89     16476
   macro avg       0.73      0.73      0.73     16476
weighted avg       0.89      0.89      0.89     16476



In [22]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score




In [33]:
model1=RandomForestClassifier(n_estimators=100)
model1.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [34]:
predict = model1.predict(X_test)
predict


array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [35]:
accuracy_score(predict,Y_test)

0.9156348628307842

In [36]:
model1.score(X_train,Y_train)

1.0