In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("C:/Users/korla/Desktop/krish codes/Feature Engineering/Feature-Engineering-Live-sessions-master/titanic.csv")
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [4]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [6]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [7]:
median = df.Age.median()

In [8]:
median

28.0

In [9]:
df.Age.fillna(median,inplace=True)

In [10]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female  28.0      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [11]:
df.Age.isnull().sum()

0

In [12]:
df.Cabin.isnull().sum()

687

In [13]:
df.Cabin.fillna('Missing',inplace=True)

In [14]:
df['Cabin_replace'] = df.Cabin.astype(str).str[0]

In [15]:
df.Cabin_replace.head()

0    M
1    C
2    M
3    C
4    M
Name: Cabin_replace, dtype: object

In [16]:
df.Embarked.isnull().sum()

2

In [17]:
a = df.Embarked.mode()[0]

In [18]:
a

'S'

In [19]:
df.Embarked.fillna(df.Embarked.mode()[0],inplace=True)

In [20]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare    Cabin Embarked Cabin_replace  
0      0         A/5 21171   7.2500  Missing        S             M  
1      0          PC 17599  71.2833      C85        C             C  
2      0  STON/O2. 3101282   7.9250  Missing        S             M  
3      0            113803  53.1000     C123        S             C  
4      0            373450   8.0500  Missing        S             M

In [21]:
df = df.drop(['Cabin'],axis=True)

In [22]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female  28.0      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Embarked Cabin_replace  
0        0         A/5 21171   7.2500        S             M  
1        0          PC 17599  71.2833        C             C  
2        0  STON/O2. 3101282   7.9250        S             M  
3        0            113803  53.1000        S             C  
4        0            373450   8.0500        S             M  
..     ...               ...      ...      ...           ...  
886      0            211536  13.0000        S             M  
887      0            112053  30.0000        S             B  
888      2        W./C. 6607  23.4500        S             M  
889      0            111369  30.0000        C             C  
890      0            370376   7.7500        Q             M  

[891 rows x 12 columns]

In [23]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked         0
Cabin_replace    0
dtype: int64

In [24]:
dummy_sex = pd.get_dummies(df['Sex'],drop_first=True)

In [25]:
dummy_sex.head()

male
0     1
1     0
2     0
3     0
4     1

In [26]:
Embarked_replace = pd.get_dummies(df['Embarked'],drop_first=True)

In [27]:
Embarked_replace.head()

Q  S
0  0  1
1  0  0
2  0  1
3  0  1
4  0  1

In [28]:
b = pd.get_dummies(df['Cabin_replace'],drop_first=True)

In [29]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female  28.0      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Embarked Cabin_replace  
0        0         A/5 21171   7.2500        S             M  
1        0          PC 17599  71.2833        C             C  
2        0  STON/O2. 3101282   7.9250        S             M  
3        0            113803  53.1000        S             C  
4        0            373450   8.0500        S             M  
..     ...               ...      ...      ...           ...  
886      0            211536  13.0000        S             M  
887      0            112053  30.0000        S             B  
888      2        W./C. 6607  23.4500        S             M  
889      0            111369  30.0000        C             C  
890      0            370376   7.7500        Q             M  

[891 rows x 12 columns]

In [30]:
df = pd.concat([df,dummy_sex,Embarked_replace,b],axis=1)

In [31]:
df



PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female  28.0      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare  ...  Q  S  B  C  D  E  F  G  M  T  
0        0         A/5 21171   7.2500  ...  0  1  0  0  0  0  0  0  1  0  
1        0          PC 17599  71.2833  ...  0  0  0  1  0  0  0  0  0  0  
2        0  STON/O2. 3101282   7.9250  ...  0  1  0  0  0  0  0  0  1  0  
3        0            113803  53.1000  ...  0  1  0  1  0  0  0  0  0  0  
4        0            373450   8.0500  ...  0  1  0  0  0  0  0  0  1  0  
..     ...               ...      ...  ... .. .. .. .. .. .. .. .. .. ..  
886      0            211536  13.0000  ...  0  1  0  0  0  0  0  0  1  0  
887      0            112053  30.0000  ...  0  1  1  0  0  0  0  0  0  0  
888      2        W./C. 6607  23.4500  ...  0  1  0  0  0  0  0  0  1  0  
889      0            111369  30.0000  ...  0  0  0  1  0  0  0  0  0  0  
890      0            370376   7.7500  ...  1  0  0  0  0  0  0  0  1  0  

[891 rows x 23 columns]

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 23 columns):
PassengerId      891 non-null int64
Survived         891 non-null int64
Pclass           891 non-null int64
Name             891 non-null object
Sex              891 non-null object
Age              891 non-null float64
SibSp            891 non-null int64
Parch            891 non-null int64
Ticket           891 non-null object
Fare             891 non-null float64
Embarked         891 non-null object
Cabin_replace    891 non-null object
male             891 non-null uint8
Q                891 non-null uint8
S                891 non-null uint8
B                891 non-null uint8
C                891 non-null uint8
D                891 non-null uint8
E                891 non-null uint8
F                891 non-null uint8
G                891 non-null uint8
M                891 non-null uint8
T                891 non-null uint8
dtypes: float64(2), int64(5), object(5), uint8(11)
memory 

In [33]:
df = df.drop(['PassengerId','Name','Sex','Ticket','Cabin_replace','Embarked'],axis=1)

In [34]:
df

Survived  Pclass   Age  SibSp  Parch     Fare  male  Q  S  B  C  D  E  F  \
0           0       3  22.0      1      0   7.2500     1  0  1  0  0  0  0  0   
1           1       1  38.0      1      0  71.2833     0  0  0  0  1  0  0  0   
2           1       3  26.0      0      0   7.9250     0  0  1  0  0  0  0  0   
3           1       1  35.0      1      0  53.1000     0  0  1  0  1  0  0  0   
4           0       3  35.0      0      0   8.0500     1  0  1  0  0  0  0  0   
..        ...     ...   ...    ...    ...      ...   ... .. .. .. .. .. .. ..   
886         0       2  27.0      0      0  13.0000     1  0  1  0  0  0  0  0   
887         1       1  19.0      0      0  30.0000     0  0  1  1  0  0  0  0   
888         0       3  28.0      1      2  23.4500     0  0  1  0  0  0  0  0   
889         1       1  26.0      0      0  30.0000     1  0  0  0  1  0  0  0   
890         0       3  32.0      0      0   7.7500     1  1  0  0  0  0  0  0   

     G  M  T  
0    0  1  0  
1    0  0  0  
2    0  1  0  
3    0  0  0  
4    0  1  0  
..  .. .. ..  
886  0  1  0  
887  0  0  0  
888  0  1  0  
889  0  0  0  
890  0  1  0  

[891 rows x 17 columns]

In [35]:
X = df.drop(['Survived'],axis=1)
y = df['Survived']

In [36]:


from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [37]:
from sklearn.tree import DecisionTreeClassifier
reg1 = DecisionTreeClassifier()
reg1.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [38]:
y_train_pred = reg1.predict(X_train)
y_train_pred[:10]

array([0, 0, 0, 0, 0, 1, 1, 0, 0, 0], dtype=int64)

In [39]:
y_train[:10]

6      0
718    0
685    0
73     0
882    0
328    1
453    1
145    0
234    0
220    1
Name: Survived, dtype: int64

In [40]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
accuracy_score(y_train,y_train_pred)

0.9815436241610739

In [41]:
confusion_matrix(y_train,y_train_pred)

array([[373,   1],
       [ 10, 212]], dtype=int64)

In [42]:
print(classification_report(y_train,y_train_pred))

              precision    recall  f1-score   support

           0       0.97      1.00      0.99       374
           1       1.00      0.95      0.97       222

    accuracy                           0.98       596
   macro avg       0.98      0.98      0.98       596
weighted avg       0.98      0.98      0.98       596



In [43]:
y_test_pred = reg1.predict(X_test)
y_test_pred[:10]

array([0, 1, 0, 1, 1, 1, 1, 0, 1, 1], dtype=int64)

In [44]:
y_test[:10]

709    1
439    0
840    0
720    1
39     1
290    1
300    1
333    0
208    1
136    1
Name: Survived, dtype: int64

In [45]:
accuracy_score(y_test,y_test_pred)

0.7457627118644068

In [46]:
confusion_matrix(y_test,y_test_pred)

array([[137,  38],
       [ 37,  83]], dtype=int64)

In [47]:
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           0       0.79      0.78      0.79       175
           1       0.69      0.69      0.69       120

    accuracy                           0.75       295
   macro avg       0.74      0.74      0.74       295
weighted avg       0.75      0.75      0.75       295



## Gridsearchcv

In [48]:
from sklearn.tree import DecisionTreeClassifier

In [49]:
reg = DecisionTreeClassifier()

In [50]:
from sklearn.model_selection import GridSearchCV
parameters = {
    
              'criterion':('gini','entropy'),
              'min_samples_split':[2,3,4,5,6,7,8,9,10],
              'max_depth':[10,11,12,13,20,25,30],
              'class_weight':('balanced',None),
              'presort':(False,True)
               
              }
grid_search = GridSearchCV(estimator=reg,
                           param_grid=parameters,
                           scoring='accuracy',
                           cv=10)
final_grid_search = grid_search.fit(X_train,y_train)

C:\Users\korla\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [50]:
final_grid_search.best_score_

0.8154362416107382

In [51]:
final_grid_search.best_params_

{'class_weight': None,
 'criterion': 'entropy',
 'max_depth': 11,
 'min_samples_split': 10,
 'presort': False}

In [52]:
reg2 = DecisionTreeClassifier(class_weight=None,criterion='entropy',max_depth=11,min_samples_split=2,presort=False)
reg2.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=11,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [53]:
y_train_pred1 = reg2.predict(X_train)
y_train_pred1[:10]

array([0, 0, 0, 0, 0, 1, 1, 0, 0, 0], dtype=int64)

In [54]:
accuracy_score(y_train,y_train_pred1)

0.9395973154362416

In [55]:
confusion_matrix(y_train,y_train_pred1)

array([[373,   1],
       [ 35, 187]], dtype=int64)

In [56]:
print(classification_report(y_train,y_train_pred1))

              precision    recall  f1-score   support

           0       0.91      1.00      0.95       374
           1       0.99      0.84      0.91       222

    accuracy                           0.94       596
   macro avg       0.95      0.92      0.93       596
weighted avg       0.94      0.94      0.94       596



In [57]:
y_test_pred1 = reg2.predict(X_test)
y_test_pred1[:10]

array([1, 0, 0, 1, 1, 1, 1, 0, 0, 1], dtype=int64)

In [58]:
accuracy_score(y_test,y_test_pred1)

0.7898305084745763

In [59]:
confusion_matrix(y_test,y_test_pred1)

array([[151,  24],
       [ 38,  82]], dtype=int64)

In [60]:
print(classification_report(y_test,y_test_pred1))

              precision    recall  f1-score   support

           0       0.80      0.86      0.83       175
           1       0.77      0.68      0.73       120

    accuracy                           0.79       295
   macro avg       0.79      0.77      0.78       295
weighted avg       0.79      0.79      0.79       295



 using Decision Tree there is an overfitting problem by finding the best Parameters also using Gridsearch CV

In [61]:
## Now Applying RandomForest 

In [51]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(X_train,y_train)

C:\Users\korla\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [52]:
y_train_pred2 = model.predict(X_train)
y_train_pred2[:10]

array([0, 0, 0, 0, 0, 1, 1, 0, 0, 0], dtype=int64)

In [53]:
accuracy_score(y_train,y_train_pred2)

0.9748322147651006

In [54]:
confusion_matrix(y_train,y_train_pred2)

array([[371,   3],
       [ 12, 210]], dtype=int64)

In [55]:
print(classification_report(y_train,y_train_pred2))

              precision    recall  f1-score   support

           0       0.97      0.99      0.98       374
           1       0.99      0.95      0.97       222

    accuracy                           0.97       596
   macro avg       0.98      0.97      0.97       596
weighted avg       0.98      0.97      0.97       596



In [56]:
y_test_pred2 = model.predict(X_test)
y_test_pred2[:10]

array([0, 0, 0, 1, 0, 1, 1, 0, 1, 1], dtype=int64)

In [57]:
accuracy_score(y_test,y_test_pred2)

0.7762711864406779

In [58]:
confusion_matrix(y_test,y_test_pred2)

array([[147,  28],
       [ 38,  82]], dtype=int64)

In [59]:
print(classification_report(y_test,y_test_pred2))

              precision    recall  f1-score   support

           0       0.79      0.84      0.82       175
           1       0.75      0.68      0.71       120

    accuracy                           0.78       295
   macro avg       0.77      0.76      0.76       295
weighted avg       0.77      0.78      0.77       295

