In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [18]:
df = pd.read_csv("C:/Users/korla/Desktop/Data/Data science materials/Unifold materials/Decision Tree/iris.csv")
df.head()


sepal.length  sepal.width  petal.length  petal.width species
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
sepal.length    150 non-null float64
sepal.width     150 non-null float64
petal.length    150 non-null float64
petal.width     150 non-null float64
species         150 non-null object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [20]:
df.species.value_counts()

Virginica     50
Versicolor    50
Setosa        50
Name: species, dtype: int64

In [23]:
df['species_label'], _ = pd.factorize(df['species'])
df['species'].unique()

array(['Setosa', 'Versicolor', 'Virginica'], dtype=object)

In [27]:
df.species_label.head()

0    0
1    0
2    0
3    0
4    0
Name: species_label, dtype: int64

In [32]:
X = df.drop(['species_label','species'],axis=1)
y = df.species_label

In [33]:
X.head()

sepal.length  sepal.width  petal.length  petal.width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [34]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: species_label, dtype: int64

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [37]:
X_train.head()

sepal.length  sepal.width  petal.length  petal.width
96            5.7          2.9           4.2          1.3
105           7.6          3.0           6.6          2.1
66            5.6          3.0           4.5          1.5
0             5.1          3.5           1.4          0.2
122           7.7          2.8           6.7          2.0

In [38]:
X_test.head()

sepal.length  sepal.width  petal.length  petal.width
73            6.1          2.8           4.7          1.2
18            5.7          3.8           1.7          0.3
118           7.7          2.6           6.9          2.3
78            6.0          2.9           4.5          1.5
76            6.8          2.8           4.8          1.4

In [39]:
y_train.head()

96     1
105    2
66     1
0      0
122    2
Name: species_label, dtype: int64

In [40]:
y_test.head()

73     1
18     0
118    2
78     1
76     1
Name: species_label, dtype: int64

In [41]:
from sklearn.tree import DecisionTreeClassifier
reg = DecisionTreeClassifier()
reg.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [42]:
y_train_pred = reg.predict(X_train)

In [44]:
y_train_pred[:10]

array([1, 2, 1, 0, 2, 1, 0, 0, 0, 1], dtype=int64)

In [45]:
y_train[:10]

96     1
105    2
66     1
0      0
122    2
67     1
28     0
40     0
44     0
60     1
Name: species_label, dtype: int64

In [46]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix


In [47]:
accuracy_score(y_train,y_train_pred)

1.0

In [49]:
print(classification_report(y_train,y_train_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        31
           1       1.00      1.00      1.00        35
           2       1.00      1.00      1.00        34

    accuracy                           1.00       100
   macro avg       1.00      1.00      1.00       100
weighted avg       1.00      1.00      1.00       100



In [50]:
confusion_matrix(y_train,y_train_pred)

array([[31,  0,  0],
       [ 0, 35,  0],
       [ 0,  0, 34]], dtype=int64)

In [51]:
y_test_pred = reg.predict(X_test)
y_test_pred[:10]

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1], dtype=int64)

In [52]:
y_test[:10]

73     1
18     0
118    2
78     1
76     1
31     0
64     1
141    2
68     1
82     1
Name: species_label, dtype: int64

In [53]:
accuracy_score(y_test,y_test_pred)

0.98

In [54]:
confusion_matrix(y_test,y_test_pred)

array([[19,  0,  0],
       [ 0, 15,  0],
       [ 0,  1, 15]], dtype=int64)

In [55]:
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.94      1.00      0.97        15
           2       1.00      0.94      0.97        16

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50



In [56]:
# lets check with the hypeparameter tuning technique using GridsearchCV

### GridsearchCV

In [57]:
from sklearn.model_selection import GridSearchCV

In [58]:
model = DecisionTreeClassifier()


In [59]:
parameters = {
    
    'criterion':['gini','entropy'],
    'max_depth':[2,3,4,5,6,7,10,11,14,20,25,30],
    'min_samples_split':[2,3,4,5,6],
    'min_samples_leaf':[2,3,4,5],
    'presort':[True,False],
    'class_weight':['balanced',None]
    }


grid_model = GridSearchCV(estimator=model,
                          param_grid=parameters,
                          scoring='accuracy',
                          cv=10)

grid_model1 = grid_model.fit(X_train,y_train)

In [60]:
grid_model1.best_params_

{'class_weight': 'balanced',
 'criterion': 'gini',
 'max_depth': 4,
 'min_samples_leaf': 3,
 'min_samples_split': 2,
 'presort': True}

In [64]:
reg1 = DecisionTreeClassifier(class_weight='balanced',criterion='gini',max_depth=4,min_samples_leaf=3,
                              min_samples_split=2,presort=True)
reg1.fit(X_train,y_train)

DecisionTreeClassifier(class_weight='balanced', criterion='gini', max_depth=4,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=3, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=True,
                       random_state=None, splitter='best')

In [68]:
y_train_pred1 = reg1.predict(X_train)
y_train_pred1[:10]


array([1, 2, 1, 0, 2, 1, 0, 0, 0, 1], dtype=int64)

In [69]:
y_train_pred[:10]

array([1, 2, 1, 0, 2, 1, 0, 0, 0, 1], dtype=int64)

In [70]:
accuracy_score(y_train,y_train_pred1)

0.96

In [71]:
confusion_matrix(y_train,y_train_pred1)

array([[31,  0,  0],
       [ 0, 32,  3],
       [ 0,  1, 33]], dtype=int64)

In [72]:
print(classification_report(y_train,y_train_pred1))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        31
           1       0.97      0.91      0.94        35
           2       0.92      0.97      0.94        34

    accuracy                           0.96       100
   macro avg       0.96      0.96      0.96       100
weighted avg       0.96      0.96      0.96       100



In [73]:
y_test_pred1 = reg1.predict(X_test)

In [74]:
y_test_pred1[:10]

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1], dtype=int64)

In [75]:
accuracy_score(y_test,y_test_pred1)

1.0

In [76]:
confusion_matrix(y_test,y_test_pred1)

array([[19,  0,  0],
       [ 0, 15,  0],
       [ 0,  0, 16]], dtype=int64)

In [77]:
print(classification_report(y_test,y_test_pred1))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        15
           2       1.00      1.00      1.00        16

    accuracy                           1.00        50
   macro avg       1.00      1.00      1.00        50
weighted avg       1.00      1.00      1.00        50

