In [41]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [42]:
from sklearn.datasets import load_digits

In [43]:
digit = load_digits()

In [44]:
digit.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [45]:
digit.target

array([0, 1, 2, ..., 8, 9, 8])

In [46]:
digit.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
digit.images

array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ..., 15.,  5.,  0.],
        [ 0.,  3., 15., ..., 11.,  8.,  0.],
        ...,
        [ 0.,  4., 11., ..., 12.,  7.,  0.],
        [ 0.,  2., 14., ..., 12.,  0.,  0.],
        [ 0.,  0.,  6., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
        [ 0.,  0.,  0., ...,  9.,  0.,  0.],
        [ 0.,  0.,  3., ...,  6.,  0.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.]],

       [[ 0.,  0.,  0., ..., 12.,  0.,  0.],
        [ 0.,  0.,  3., ..., 14.,  0.,  0.],
        [ 0.,  0.,  8., ..., 16.,  0.,  0.],
        ...,
        [ 0.,  9., 16., ...,  0.,  0.,  0.],
        [ 0.,  3., 13., ..., 11.,  5.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.]],

       ...,

       [[ 0.,  0.,  1., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ...,  2.,  1.,  0.],
        [ 0.,  0., 16., ..., 16.,  5.,  0.

In [48]:
df = pd.DataFrame(digit.data)
df.head()

0    1    2     3     4     5    6    7    8    9   ...   54   55   56  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  5.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  9.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

    57   58    59    60    61   62   63  
0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4  0.0  0.0   2.0  16.0   4.0  0.0  0.0  

[5 rows x 64 columns]

In [49]:
df['target'] = digit.target

In [50]:
df.head()

0    1    2     3     4     5    6    7    8    9  ...   55   56   57  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  0.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

    58    59    60    61   62   63  target  
0  6.0  13.0  10.0   0.0  0.0  0.0       0  
1  0.0  11.0  16.0  10.0  0.0  0.0       1  
2  0.0   3.0  11.0  16.0  9.0  0.0       2  
3  7.0  13.0  13.0   9.0  0.0  0.0       3  
4  0.0   2.0  16.0   4.0  0.0  0.0       4  

[5 rows x 65 columns]

In [51]:
X = df.drop(['target'],axis=1)
y = df.target

In [52]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [53]:
X_train.head()

0    1     2     3     4     5    6    7    8    9   ...    54   55  \
428   0.0  0.0   0.0   1.0  12.0   7.0  0.0  0.0  0.0  0.0  ...   0.0  0.0   
1357  0.0  0.0   1.0  15.0  15.0   2.0  0.0  0.0  0.0  0.0  ...   0.0  0.0   
1185  0.0  1.0  12.0  15.0  16.0  13.0  1.0  0.0  0.0  4.0  ...   0.0  0.0   
31    0.0  0.0   2.0  13.0   8.0   0.0  0.0  0.0  0.0  0.0  ...  16.0  2.0   
1603  0.0  2.0  11.0  14.0  14.0   9.0  0.0  0.0  0.0  3.0  ...   0.0  0.0   

       56   57    58    59    60    61    62   63  
428   0.0  0.0   0.0   3.0  15.0  13.0   0.0  0.0  
1357  0.0  0.0   1.0  14.0  16.0   7.0   0.0  0.0  
1185  0.0  2.0  13.0  16.0  10.0   0.0   0.0  0.0  
31    0.0  0.0   2.0  15.0  13.0  14.0  13.0  2.0  
1603  0.0  1.0  15.0  13.0   1.0   0.0   0.0  0.0  

[5 rows x 64 columns]

In [54]:
X_test.head()

0    1     2     3     4     5    6    7    8    9   ...    54   55  \
1245  0.0  0.0   0.0   7.0  12.0   0.0  0.0  0.0  0.0  0.0  ...  16.0  2.0   
220   0.0  0.0  11.0  16.0   8.0   0.0  0.0  0.0  0.0  6.0  ...   0.0  0.0   
1518  0.0  0.0   8.0  15.0  12.0   4.0  0.0  0.0  0.0  5.0  ...   7.0  0.0   
438   0.0  0.0   2.0  12.0  12.0  12.0  9.0  2.0  0.0  0.0  ...   0.0  0.0   
1270  0.0  2.0  13.0  16.0  10.0   0.0  0.0  0.0  0.0  6.0  ...  14.0  0.0   

       56   57    58    59    60    61   62   63  
1245  0.0  0.0   0.0   9.0  14.0  14.0  5.0  0.0  
220   0.0  0.0  13.0  16.0  11.0   1.0  0.0  0.0  
1518  0.0  0.0  13.0  16.0  15.0   8.0  0.0  0.0  
438   0.0  0.0   3.0  15.0   3.0   0.0  0.0  0.0  
1270  0.0  3.0  15.0  16.0  16.0  10.0  1.0  0.0  

[5 rows x 64 columns]

In [55]:
y_train.head()

428     1
1357    1
1185    8
31      9
1603    3
Name: target, dtype: int32

In [56]:
y_test.head()

1245    6
220     9
1518    3
438     7
1270    2
Name: target, dtype: int32

In [57]:
len(X_train)

1203

In [58]:
len(X_test)

594

In [59]:
len(y_train)

1203

In [60]:
len(X_test)

594

In [61]:
from sklearn.svm import SVC

In [62]:
reg = SVC(kernel='linear')

In [63]:
reg.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [64]:
y_test_pred = reg.predict(X_test)


In [65]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix


In [66]:
accuracy_score(y_test,y_test_pred)

0.9797979797979798

In [67]:
reg.score(X_train,y_train)

1.0